### ISSUE TITLE
Auth cannot be switched off

### ISSUE THREAD

**Issue by strausmann** [intergral/mkdocs-gitlab-review-plugin#3]
The Auth parameter cannot be set to false. Neither via the default setting nor via "auth: false".

```
plugins:
  - gitlab_review:
      gitlab_url: https://git.domain.de
      script_url: https://git.domain.de/assets/webpack/visual_review_toolbar.js
      auth: false
```
